### PR TITLE
Add books

### PR DESCRIPTION
**Pull request by hamidazim321**
In this PR:
* Me and my partner have worked collaboratively
* We have implemented all the required features in the project requirements
* We have implemented the correct layout without using CSS

**NOTE**
* Only 1 redundant style is added in the styles.css file, with the advice microverse students, because empty CSS file causes stylelint errors

### CODE REVIEW

**Review by Shisui6 — COMMENTED** [review]
Hi @hamidazim321 and @hetrox8, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛠️

You have submitted a HTML, CSS and JS project without the stylelint linter checks. Please make sure your project contains all the relevant linter checks (excluding webhint).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DeliceLydia** [comment]
## Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional README you can refer to this [template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by TedLivist — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @hamidazim321 and @hetrox8,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### - If you do not intend deploying the app then kindly remove the live demo section and its link in the Table of Contents, instead of just writing "N/A".

  image

### - Kindly remove this dummy text from your README.

  kfkfor

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
Hi @hamidazim321 you are yet to remove the part of the README I highlighted. The one at the bottom of the README.

**Comment by hamidazim321** [comment]
Hey @TedLivist , I have removed the Live Demo from README. You can check

**Comment by TedLivist** [comment]
@hamidazim321, there are two parts. The live demo is the first one.

image

**Comment by hamidazim321** [comment]
@TedLivist I have just removed that one too, you can check again. Should I ask for another review on Dashboard or will you be reviewing it now?

**Review by TedLivist — APPROVED** [review]
## STATUS: APPROVED ✔️ ✔️

Hi @hamidazim321 and @hetrox8,

✔️ Books are loaded from `localStorage`

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
